version: 2

project_name: SyncCommander

before:
  hooks:
    - go mod download

builds:
  - id: sc
    main: .
    binary: sc_{{ .Os }}_{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

snapshot:
  version_template: "{{ incpatch .Version }}-next"
