package transport

import "sc/model"

// The optional capability interfaces are picked up by type assertion, so a
// renamed or mistyped method would silently drop a feature. These lines make
// the compiler check every backend against what it is meant to offer.
var (
	_ model.Backend            = (*LocalBackend)(nil)
	_ model.ChecksumProber     = (*LocalBackend)(nil)
	_ model.Resumer            = (*LocalBackend)(nil)
	_ model.SeekableOpener     = (*LocalBackend)(nil)
	_ model.LocalFS            = (*LocalBackend)(nil)
	_ model.Backend            = (*SFTPBackend)(nil)
	_ model.ChecksumProber     = (*SFTPBackend)(nil)
	_ model.Resumer            = (*SFTPBackend)(nil)
	_ model.SeekableOpener     = (*SFTPBackend)(nil)
	_ model.Backend            = (*SCPBackend)(nil)
	_ model.ChecksumProber     = (*SCPBackend)(nil)
	_ model.Resumer            = (*SCPBackend)(nil)
	_ model.SeekableOpener     = (*SCPBackend)(nil)
	_ model.RecursivePreloader = (*SCPBackend)(nil)
	_ model.Backend            = (*RsyncSSHBackend)(nil)
	_ model.ChecksumProber     = (*RsyncSSHBackend)(nil)
	_ model.ChecksumPrefetcher = (*RsyncSSHBackend)(nil)
	_ model.Resumer            = (*RsyncSSHBackend)(nil)
	_ model.SeekableOpener     = (*RsyncSSHBackend)(nil)
	_ model.LocalSender        = (*RsyncSSHBackend)(nil)
	_ model.LocalReceiver      = (*RsyncSSHBackend)(nil)
	_ model.BatchSender        = (*RsyncSSHBackend)(nil)
	_ model.RecursivePreloader = (*RsyncSSHBackend)(nil)
	_ ProgressOwner            = (*RsyncSSHBackend)(nil)
	_ model.Backend            = (*RsyncBackend)(nil)
	_ model.ChecksumProber     = (*RsyncBackend)(nil)
	_ model.ChecksumPrefetcher = (*RsyncBackend)(nil)
	_ model.LocalSender        = (*RsyncBackend)(nil)
	_ model.LocalReceiver      = (*RsyncBackend)(nil)
	_ model.RecursivePreloader = (*RsyncBackend)(nil)
	_ ProgressOwner            = (*RsyncBackend)(nil)
	_ model.Backend            = (*FTPBackend)(nil)
	_ model.ChecksumProber     = (*FTPBackend)(nil)
	_ model.Resumer            = (*FTPBackend)(nil)
	_ model.SeekableOpener     = (*FTPBackend)(nil)
	_ model.Backend            = (*WebDAVBackend)(nil)
	_ model.ChecksumProber     = (*WebDAVBackend)(nil)
	_ model.SeekableOpener     = (*WebDAVBackend)(nil)
	_ model.RecursivePreloader = (*WebDAVBackend)(nil)
	_ model.Backend            = (*ResticBackend)(nil)
	_ model.ChecksumProber     = (*ResticBackend)(nil)
	_ model.SeekableOpener     = (*ResticBackend)(nil)
	_ model.RecursivePreloader = (*ResticBackend)(nil)
	_ model.Backend            = (*RcloneBackend)(nil)
	_ model.ChecksumProber     = (*RcloneBackend)(nil)
	_ model.SeekableOpener     = (*RcloneBackend)(nil)
	_ model.RecursivePreloader = (*RcloneBackend)(nil)
	_ model.Backend            = (*FakeBackend)(nil)
	_ model.ChecksumProber     = (*FakeBackend)(nil)
	_ model.SeekableOpener     = (*FakeBackend)(nil)
	_ model.Backend            = (*lazyBackend)(nil)
	_ model.LivenessManaged    = (*lazyBackend)(nil)
	_ model.Resumer            = (*lazyBackend)(nil)
	_ model.BatchSender        = (*lazyBackend)(nil)
)
